from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('a-propos/', views.about, name='about'),
    path('expertise/', views.expertise, name='expertise'),
    path('formations/', views.courses, name='courses'),
    path('formations/calendrier/', views.training_calendar, name='training_calendar'),
    path('formations/<int:pk>/', views.course_detail, name='course_detail'),
    path('demande-devis/', views.quote_request, name='quote_request'),
    path('formation-sur-mesure/', views.custom_training, name='custom_training'),
    path('contact/', views.contact, name='contact'),
    path('actualites/', views.articles, name='articles'),
    path('ressources/', views.resources, name='resources'),
    path('conditions-generales/', views.terms, name='terms'),
    path('confidentialite/', views.privacy, name='privacy'),
    path('gestion/login/', views.custom_admin_login, name='custom_admin_login'),
    path('gestion/logout/', views.admin_logout, name='admin_logout'),
    path('gestion/', views.admin_dashboard, name='admin_dashboard'),
    path('gestion/categories/', views.admin_categories, name='admin_categories'),
    path('gestion/categories/nouveau/', views.admin_category_new, name='admin_category_new'),
    path('gestion/categories/<int:pk>/modifier/', views.admin_category_edit, name='admin_category_edit'),
    path('gestion/categories/<int:pk>/supprimer/', views.admin_category_delete, name='admin_category_delete'),
    path('gestion/formations/', views.admin_formations, name='admin_formations'),
    path('gestion/formations/nouveau/', views.admin_formations_new, name='admin_formations_new'),
    path('gestion/formations/<int:pk>/modifier/', views.admin_formation_edit, name='admin_formation_edit'),
    path('gestion/formations/<int:pk>/supprimer/', views.admin_formation_delete, name='admin_formation_delete'),
    path('gestion/actualites/', views.admin_articles, name='admin_articles'),
    path('gestion/actualites/nouveau/', views.admin_articles_new, name='admin_articles_new'),
    path('gestion/actualites/<int:pk>/modifier/', views.admin_article_edit, name='admin_article_edit'),
    path('gestion/actualites/<int:pk>/supprimer/', views.admin_article_delete, name='admin_article_delete'),
    path('gestion/ressources/', views.admin_resources, name='admin_resources'),
    path('gestion/ressources/nouveau/', views.admin_resources_new, name='admin_resources_new'),
    path('gestion/ressources/<int:pk>/modifier/', views.admin_resource_edit, name='admin_resource_edit'),
    path('gestion/ressources/<int:pk>/supprimer/', views.admin_resource_delete, name='admin_resource_delete'),
    path('gestion/messages/', views.admin_messages, name='admin_messages'),
    path('gestion/messages/nouveau/', views.admin_messages_new, name='admin_messages_new'),
    path('gestion/messages/<int:pk>/modifier/', views.admin_message_edit, name='admin_message_edit'),
    path('gestion/messages/<int:pk>/supprimer/', views.admin_message_delete, name='admin_message_delete'),
    path('gestion/demandes/', views.admin_training_requests, name='admin_training_requests'),
    path('gestion/profil/', views.user_profile, name='user_profile'),
    path('gestion/comptes/', views.admin_accounts, name='admin_accounts'),
    path('gestion/comptes/nouveau/', views.admin_account_new, name='admin_account_new'),
    path('gestion/seo/', views.admin_seo, name='admin_seo'),
    path('robots.txt', views.robots_txt, name='robots_txt'),
    path('sitemap.xml', views.sitemap_xml, name='sitemap_xml'),
]
