# Generated by Django 6.1 on 2026-09-15 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0004_alter_course_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('organization', models.CharField(blank=True, max_length=150)),
                ('request_type', models.CharField(choices=[('devis', 'Demande de devis'), ('sur_mesure', 'Formation sur mesure')], max_length=20)),
                ('participants', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='modality',
            field=models.CharField(choices=[('presentiel', 'Présentiel'), ('en_ligne', 'En ligne'), ('hybride', 'Présentiel / En ligne')], default='presentiel', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('inscriptions', 'Inscriptions ouvertes'), ('bientot', 'Bientôt disponible'), ('complet', 'Complet'), ('terminee', 'Formation terminée')], default='bientot', max_length=20),
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('organization', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='siteapp.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
